# Generated by Django 4.2.30 on 2026-05-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LaunchStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_concept", models.CharField(max_length=255)),
                ("genre", models.CharField(max_length=100)),
                ("target_audience", models.CharField(max_length=255)),
                ("launch_recommendations", models.JSONField(default=dict)),
                (
                    "suggested_pricing",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("market_positioning", models.TextField()),
                ("best_release_timing", models.CharField(max_length=255)),
                ("viral_marketing_suggestions", models.JSONField(default=list)),
                ("competing_games", models.JSONField(default=list)),
                ("differentiation_factors", models.JSONField(default=list)),
                ("risk_factors", models.JSONField(default=list)),
                ("confidence_score", models.FloatField(help_text="0-100 scale")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Trend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("genre", "Genre"),
                            ("mechanic", "Mechanic"),
                            ("aesthetic", "Aesthetic"),
                            ("platform", "Platform"),
                            ("technology", "Technology"),
                            ("monetization", "Monetization"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("keywords", models.JSONField(default=list)),
                ("momentum_score", models.FloatField(help_text="0-100 scale")),
                (
                    "growth_rate",
                    models.FloatField(default=0, help_text="Percentage growth"),
                ),
                ("search_volume", models.IntegerField(default=0)),
                ("market_gap", models.TextField(blank=True)),
                (
                    "opportunity_level",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("supporting_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-momentum_score"],
                "indexes": [
                    models.Index(
                        fields=["category", "-momentum_score"],
                        name="api_trend_categor_6fb391_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlayerSentiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_title", models.CharField(max_length=255)),
                (
                    "sentiment_type",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("reddit", "Reddit"),
                            ("youtube", "YouTube"),
                            ("tiktok", "TikTok"),
                            ("steam", "Steam"),
                            ("twitter", "Twitter"),
                            ("discord", "Discord"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sentiment_score", models.FloatField(help_text="-1 to 1 scale")),
                ("comment", models.TextField()),
                ("key_themes", models.JSONField(default=list)),
                (
                    "engagement_metric",
                    models.IntegerField(default=0, help_text="Likes, upvotes, views"),
                ),
                ("url", models.URLField(blank=True)),
                ("raw_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["game_title", "source", "-created_at"],
                        name="api_players_game_ti_08d0bb_idx",
                    ),
                    models.Index(
                        fields=["sentiment_type"], name="api_players_sentime_9cd814_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=500)),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("niche_discovery", "Niche Discovery"),
                            ("competitor_analysis", "Competitor Analysis"),
                            ("trend_analysis", "Trend Analysis"),
                            ("market_gap", "Market Gap"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ai_insights", models.JSONField(default=dict)),
                ("trending_mechanics", models.JSONField(default=list)),
                ("rising_genres", models.JSONField(default=list)),
                ("market_gaps", models.JSONField(default=list)),
                ("monetization_opportunities", models.JSONField(default=list)),
                ("confidence_score", models.FloatField(help_text="0-100 scale")),
                ("raw_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["analysis_type", "-created_at"],
                        name="api_marketa_analysi_280e0a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("developer", models.CharField(max_length=255)),
                ("genre", models.JSONField(default=list)),
                ("tags", models.JSONField(default=list)),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("rating", models.FloatField(blank=True, null=True)),
                ("review_count", models.IntegerField(default=0)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("steam", "Steam"),
                            ("epic", "Epic Games"),
                            ("itch", "itch.io"),
                            ("mobile", "Mobile"),
                            ("roblox", "Roblox"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("scraped_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["platform", "-updated_at"],
                        name="api_game_platfor_f64816_idx",
                    ),
                    models.Index(fields=["genre"], name="api_game_genre_40f9ec_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_title", models.CharField(max_length=255)),
                ("developer", models.CharField(max_length=255)),
                ("platform", models.CharField(max_length=20)),
                ("genre", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("rating", models.FloatField(blank=True, null=True)),
                ("review_count", models.IntegerField(default=0)),
                ("downloads", models.IntegerField(blank=True, null=True)),
                (
                    "price_change",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("engagement_spike", models.BooleanField(default=False)),
                ("social_mentions", models.IntegerField(default=0)),
                ("sentiment_overview", models.JSONField(default=dict)),
                ("url", models.URLField()),
                ("last_scraped", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["platform", "genre"],
                        name="api_competi_platfor_e440be_idx",
                    ),
                    models.Index(
                        fields=["-updated_at"], name="api_competi_updated_3407f9_idx"
                    ),
                ],
            },
        ),
    ]
