# Generated by Django 4.2.30 on 2026-05-23 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=255, unique=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("steam", "Steam"),
                            ("itch_io", "itch.io"),
                            ("epic", "Epic Games Store"),
                            ("google_trends", "Google Trends"),
                            ("social_media", "Social Media"),
                        ],
                        max_length=50,
                    ),
                ),
                ("query", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("results_count", models.IntegerField(default=0)),
                ("raw_data", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="api_scrapin_status_286edc_idx",
                    ),
                    models.Index(
                        fields=["source"], name="api_scrapin_source_22f510_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScrapedGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("developer", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(unique=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("rating", models.FloatField(blank=True, null=True)),
                ("review_count", models.IntegerField(default=0)),
                ("genres", models.JSONField(default=list)),
                ("tags", models.JSONField(default=list)),
                ("description", models.TextField(blank=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("download_count", models.IntegerField(blank=True, null=True)),
                (
                    "trending_score",
                    models.FloatField(
                        default=0.0, help_text="0-100 trending popularity"
                    ),
                ),
                ("engagement_metrics", models.JSONField(default=dict)),
                ("raw_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scraping_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="api.scrapingjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-trending_score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["platform", "-trending_score"],
                        name="api_scraped_platfor_9e65da_idx",
                    ),
                    models.Index(
                        fields=["genres"], name="api_scraped_genres_90e542_idx"
                    ),
                ],
            },
        ),
    ]
