# Generated by Django 4.2.30 on 2026-05-24 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_tier_usersubscription_tokenusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('feature_view', 'Feature Viewed'), ('scrape_started', 'Scraping Started'), ('scrape_completed', 'Scraping Completed'), ('api_call', 'API Call'), ('export', 'Data Exported'), ('report_generated', 'Report Generated'), ('upgrade_clicked', 'Upgrade Clicked'), ('page_visited', 'Page Visited')], max_length=50)),
                ('event_name', models.CharField(max_length=255)),
                ('page', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(default=dict, help_text='Custom event data')),
                ('duration_seconds', models.FloatField(blank=True, help_text='How long the action took', null=True)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('paid', 'Paid'), ('uncollectible', 'Uncollectible')], default='sent', max_length=20)),
                ('pdf_url', models.URLField(blank=True)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=255, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='scrapedgame',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveIndex(
            model_name='scrapedgame',
            name='api_scraped_platfor_9e65da_idx',
        ),
        migrations.RemoveIndex(
            model_name='scrapedgame',
            name='api_scraped_genres_90e542_idx',
        ),
        migrations.RemoveField(
            model_name='scrapedgame',
            name='description',
        ),
        migrations.RemoveField(
            model_name='scrapedgame',
            name='download_count',
        ),
        migrations.RemoveField(
            model_name='scrapedgame',
            name='engagement_metrics',
        ),
        migrations.RemoveField(
            model_name='scrapedgame',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='scrapedgame',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='scrapedgame',
            name='scraping_job',
        ),
        migrations.RemoveField(
            model_name='scrapedgame',
            name='trending_score',
        ),
        migrations.AddIndex(
            model_name='scrapedgame',
            index=models.Index(fields=['platform', '-updated_at'], name='api_scraped_platfor_048c91_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tier'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.payment'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tier'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='api_payment_user_id_bab04b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='api_payment_status_c61efc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', '-created_at'], name='api_invoice_user_id_8dad79_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='api_invoice_status_d10657_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['user', '-created_at'], name='api_analyti_user_id_dd2a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type'], name='api_analyti_event_t_1638f1_idx'),
        ),
    ]
