# Generated by Django 4.2.30 on 2026-05-24 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_analyticsevent_invoice_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('change', 'Tier Change')], max_length=20)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('amount_charged', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prorated_credit', models.DecimalField(decimal_places=2, default=0, help_text='Credit from previous tier', max_digits=10)),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downgrade_from', to='api.tier')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tier_change', to='api.payment')),
                ('to_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_to', to='api.tier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tier Change',
                'verbose_name_plural': 'Tier Changes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_tiercha_user_id_4099d5_idx'), models.Index(fields=['status'], name='api_tiercha_status_692d07_idx')],
            },
        ),
    ]
