# Generated by Django 6.0.3 on 2026-05-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tierchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Generated PDF invoice file', null=True, upload_to='invoices/'),
        ),
    ]
