# Generated by Django 6.0.3 on 2026-05-25 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_invoice_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(db_index=True, help_text='Stripe event ID', max_length=255, unique=True)),
                ('event_type', models.CharField(help_text='e.g., payment_intent.succeeded', max_length=100)),
                ('api_version', models.CharField(blank=True, max_length=20)),
                ('raw_data', models.JSONField(help_text='Full Stripe webhook event payload')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('retry_count', models.IntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='api.payment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['stripe_event_id'], name='api_webhook_stripe__1cc0ee_idx'), models.Index(fields=['event_type'], name='api_webhook_event_t_165d76_idx'), models.Index(fields=['status'], name='api_webhook_status_3a5008_idx'), models.Index(fields=['user', '-received_at'], name='api_webhook_user_id_667667_idx')],
            },
        ),
    ]
